### ISSUE TITLE
Could you add identifierSpace and schemaSpace in the metadata?

### ISSUE THREAD

**Issue by ettorerizza** [mphilli/LoC-reconcile#1]
Hi @mphilli, thank you for your great work! Just to let you know that in OpenRefine 3.1, [some users of your services have experienced data loss](https://github.com/OpenRefine/OpenRefine/issues/1936). 

It seems that the bug would be linked to the absence of values (if only by default) to identifySpace and schemaSpace in the metadata object. Here is an example of dummy values in [LoCreconcile.py](https://github.com/mphilli/LoC-reconcile/blob/master/LoCreconcile.py). 

```
metadata = {
    "name": "LC Reconciliation Service",
    "identifierSpace" : "http://localhost/identifier",
    "schemaSpace" : "http://localhost/schema",
    "defaultTypes": query_types,
    "view": {
        "url": "{{id}}"
    },
}
```

The issue will be fixed in the next version of OR, but in the meantime, it would be nice if you could add some uri for these items. :)

Kind regards.

**Comment by mphilli** [comment]
Hello, 

While I won't be making any changes myself, I will merge any pull requests for changes/updates aimed at fixing this issue.

**Comment by ettorerizza** [comment]
Hello, 

Thank you for your response. I'm not sure what value to introduce for the library of congress. In the next version of OpenRefine, services that do not mention these two elements will be assigned default values, so I will make a pull request with these values. I see that the [opencorporates reconciliation service](https://opencorporates.com/reconcile) kept the freebase defaults, which no longer exists and has nothing to do with opencoprorates. This does not prevent the service from working.
