### ISSUE TITLE
Unable to install: lxml errors

### ISSUE THREAD

**Issue by dezel002** [mphilli/LoC-reconcile#3]
I'm attempting to install the requirements for the reconciler and keep running into error messages. lxml appears to be the culprit, but I don't know how to diagnose it. A colleague suggested I try installing lxml separately, and I did that, but then the reconciler program uninstalled my existing lxml, and failed when trying to reinstall it. I attempted to attach my error logs, but GitHub is telling me that it won't accept the file type (even though they are .txt). I can paste them in, but they are very long--let me know what you advise.

**Comment by mphilli** [comment]
Difficult to diagnose without a stack trace. Let me know if you figure out a way to share what's going on.

**Comment by mphilli** [comment]
I removed the version requirement from lxml in the requirements file so it will grab the latest version by default; I don't know if that will break anything, but it may solve the installation issue.

**Comment by dezel002** [comment]
That seemed to do the trick--thank you!
